### PR TITLE
Fix containment Y-position when contain is true and pan-zoom is scaled in or out

### PR DESCRIPTION
**Pull request by awartani**
We noticed an issue when we used this great library, where if `contain: true`, the containment dimensions are invalid in case of zoom in/out.

We found a similar [issue opened](https://github.com/timmywil/jquery.panzoom/issues/271) with an [excellent example](http://jsbin.com/cidebod/edit?html,css,js,output).

Also, the issue is visible in your "Containment within the parent element" demo.

### CODE REVIEW

**Comment by timmywil** [comment]
Thanks for the PR! 😃 

However, I'm concerned that the X-position code isn't getting the same changes. Why does this only affect the Y-position?

**Comment by awartani** [comment]
@timmywil I think X-Position has some issues as well. Unfortunately I didn't take a look at it yet but from general testing I can see a bunch of issues.

I just pushed another fix:
1. Add a handle to invert, and automatic containment.
1. Handle container border.

**Comment by awartani** [comment]
@timmywil updated the source code to support x-axis position. Please take a look.

I think the code handles this but I don't know the actual cases that this code was written for:

```
if (this.$parent.css('textAlign') !== 'center' || $.css(this.elem, 'display') !== 'inline') ...
```

**Comment by awartani** [comment]
Also, what's the issue with Node 6 (travis-ci failed because of that)?

**Comment by Spooner** [comment]
I'm using this patch now. Latest version had this bug, so I was using an older one (that had another bug), so now I've got everything working at once. Please pull :man_dancing:

**Comment by awartani** [comment]
@timmywil if the test fixed, will you merge this?

**Comment by hamoid** [comment]
Without this fix `contain: 'invert'` does not work for me. 

For instance an image that should move between 0px and -360px instead moves between 180px and -180px. The effect is that the panned image has an empty 180px margin on the top side.

**Pull request closed without merging**
