### PR TITLE
Adds code to precalculate the scaled dimensions

### PR DESCRIPTION
**Pull request by satsukitv**
### PR Checklist
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not *master*.
- [ ] I have run `grunt` against my changes and both linting and tests pass. (`Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.`)
- [ ] I have added tests to prove my fix is affective or my feature works. This can be done in the form of unit tests in `test/bdd/test.js` or a new demo on `demo/index.html`.
- [N/A] I have added or edited necessary documentation in the README.md (if appropriate). 

### Description
When zooming out on focal or with a zoom "button" with `contain: invert` set as an option, the image will  not be forced inside the container's edges, creating whitespace. This is due to the pre-scale image dimensions being used to calculate its final translation position. Addresses issue #298

Unable to get tests to run on my machine:
`Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.`

**Fixes**: #298

### CODE REVIEW

**Comment by jcnventura** [comment]
This doesn't seem to make a difference.

**Comment by satsukitv** [comment]
without change: https://gyazo.com/bc870402a234e63bd562266fe7102187
with change: https://gyazo.com/2820783a502a88f904a0afdaa06ba237
codepen to demonstrate bug:  http://codepen.io/satsukitv/pen/GmRmbo
codepen to demonstrate fix: http://codepen.io/satsukitv/pen/BRaZWd

Steps to reproduce:

1. Zoom in and pan to a corner.
2. Zoom out using the *button* or *mousewheel*, not the range.
3. The image will not be properly contained after scaling in the bugged code. The fix should show the image properly contained.

**Comment by jcnventura** [comment]
Can you rebase and re-commit? The tests should now run

**Comment by jcnventura** [comment]
Merged this on top of #336, and ran the tests.. This simple change indeed fixed the containment during zoom out.

**Pull request closed without merging**
